#!/bin/bash
# Script to reduce the size of pdfs
# pdfshrink in out
# if no out file is specified, a new file is created with the input filename.shrink.pdf
doprinter(){
gs -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/printer -sOutputFile="$out" "$filename.$extension"
}
doprepress(){
gs -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/prepress -sOutputFile="$out" "$filename.$extension"
}
doscreen(){
gs -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/screen -sOutputFile="$out" "$filename.$extension"
}

SHORT=psePh
LONG=printer,screen,prepress,ebook

PARSED=`getopt --options $SHORT --longoptions $LONG --name "$0" -- "$@"`
eval set -- "$PARSED"


type=screen
 while true; do
    case "$1" in
        -p|--printer)
            type=printer
            shift
            ;;
        -e|--ebook)
            type=ebook
            shift
            ;;
        -s|--screen)
            type=screen
            shift
            ;;
        -P|--prepress)
            type=prepress
            shift
            ;;
         --)
            shift
            break
            ;;
        -h|--help)
            echo "Usage: pdfshrink [-spP | --screen  --printer --prepress] infile [outfile]"
            shift
            exit
            ;;
        *)
            type=screen
            shift
            ;;
    esac
done

if [ -z "$2" ]
  then
  filename=$(basename "$1")
  extension="${filename##*.}"
  filename="${filename%.*}"
  out=$filename.shrink.$extension
  echo "$1 to $out"
else
  out=$2
  
fi

gs -dNOPAUSE -dBATCH -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/$type -sOutputFile="$out" "$1"





